//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontakt()
        {
            this.Povrces = new HashSet<Povrce>();
        }
    
        public System.DateTime DATUM { get; set; }
        public int DobavljacID { get; set; }
        public int DirektorJMBG { get; set; }
    
        public virtual Dobavljac Dobavljac { get; set; }
        public virtual Direktor Direktor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Povrce> Povrces { get; set; }
    }
}
