//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseContainer : DbContext
    {
        public databaseContainer()
            : base("name=databaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Kupac> Kupacs { get; set; }
        public virtual DbSet<Ugovor> Ugovors { get; set; }
        public virtual DbSet<Porudzbina> Porudzbinas { get; set; }
        public virtual DbSet<Prosledjuje> Prosledjujes { get; set; }
        public virtual DbSet<Dobavljac> Dobavljacs { get; set; }
        public virtual DbSet<Kontakt> Kontakts { get; set; }
        public virtual DbSet<Magacin> Magacins { get; set; }
        public virtual DbSet<Povrce> Povrces { get; set; }
        public virtual DbSet<Odvaja> Odvajas { get; set; }
        public virtual DbSet<Tovari> Tovaris { get; set; }
        public virtual DbSet<Vozi> Vozis { get; set; }
    }
}
