//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porudzbina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Porudzbina()
        {
            this.Prosledjujes = new HashSet<Prosledjuje>();
        }
    
        public int UgovorKupacKID { get; set; }
        public int UgovorDirektorJMBG { get; set; }
        public int ID { get; set; }
        public int MenadzerJMBG { get; set; }
    
        public virtual Ugovor Ugovor { get; set; }
        public virtual Menadzer Menadzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prosledjuje> Prosledjujes { get; set; }
    }
}
