//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Povrce
    {
        public int VID { get; set; }
        public string VNAZIV { get; set; }
        public string ZEMLJAP { get; set; }
        public string ROK { get; set; }
        public int MagacinMID { get; set; }
        public int KontaktDobavljacID { get; set; }
        public int KontaktDirektorJMBG { get; set; }
        public int ProsledjujePorudzbinaID { get; set; }
        public int ProsledjujeMagacionerJMBG1 { get; set; }
    
        public virtual Magacin Magacin { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual Prosledjuje Prosledjuje { get; set; }
        public virtual Odvaja Odvajas { get; set; }
    }
}
