//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozi
    {
        public int KupacKID { get; set; }
        public int TovariVozacJMBG { get; set; }
        public int TovariOdvajaPovrceMagacinMID { get; set; }
        public int TovariOdvajaPovrceVID { get; set; }
    
        public virtual Kupac Kupac { get; set; }
        public virtual Tovari Tovari { get; set; }
    }
}
